// apps/playground/src/components/board/BoardElement.tsx
import type { MilanoteNode } from "@milanote-api/parser";
import { ExternalLink, FileText, ImageIcon } from "lucide-react";
import type { ReactNode } from "react";

import { Badge } from "@/components/ui/badge.tsx";
import {
  formatCompactDate,
  getComments,
  getFileName,
  getFileSize,
  getImageUrl,
  getLinkUrl,
  getNodeChildren,
  getNodeDescription,
  getNodeLabel,
  getNodeTypeCode,
  getNodeTypeLabel,
  getTableRows,
  getTaskDueDate,
  getUnknownKind,
  isTaskComplete,
} from "@/utils/boardModel.ts";

interface BoardElementProps {
  depth?: number;
  node: MilanoteNode;
}

function Children({ children, depth }: { children: readonly MilanoteNode[]; depth: number }) {
  return children.map((child) => <BoardElement key={child.id} node={child} depth={depth + 1} />);
}

function Heading({
  children,
  depth,
  className,
}: {
  children: ReactNode;
  className?: string;
  depth: number;
}) {
  return (
    <div className={className} role="heading" aria-level={Math.min(depth + 2, 6)}>
      {children}
    </div>
  );
}

export function BoardElement({ depth = 0, node }: BoardElementProps) {
  const children = getNodeChildren(node);
  const label = getNodeLabel(node);
  const description = getNodeDescription(node);
  const typeCode = getNodeTypeCode(node.type);
  const typeLabel = getNodeTypeLabel(node.type);
  const imageUrl = getImageUrl(node);
  const linkUrl = getLinkUrl(node);

  switch (node.type) {
    case "COLUMN":
      return (
        <section className="min-w-0 rounded-xl border bg-card p-3 shadow-sm">
          <header className="mb-3 flex items-start justify-between gap-3 border-b pb-3">
            <div className="min-w-0">
              <Badge variant="outline">{typeCode}</Badge>
              <Heading depth={depth} className="mt-2 break-words text-sm font-semibold">
                {label}
              </Heading>
            </div>
            <span className="shrink-0 font-mono text-xs text-muted-foreground">
              {children.length}
            </span>
          </header>
          {children.length > 0 ? (
            <div className="grid gap-2.5">
              <Children children={children} depth={depth} />
            </div>
          ) : (
            <p className="py-5 text-center text-xs text-muted-foreground">Empty column</p>
          )}
        </section>
      );

    case "BOARD":
      return (
        <section className="min-w-0 rounded-xl border bg-card p-3 shadow-sm">
          <header className="mb-3 flex items-center justify-between gap-3">
            <Heading depth={depth} className="min-w-0 truncate text-sm font-semibold">
              {label}
            </Heading>
            <Badge variant="outline">{typeCode}</Badge>
          </header>
          <div className="grid gap-2.5">
            <Children children={children} depth={depth} />
          </div>
        </section>
      );

    case "CARD":
      return (
        <article className="min-w-0 rounded-lg border border-primary/15 bg-primary/5 p-3">
          <div className="mb-2 flex items-center justify-between gap-2">
            <Badge variant="secondary">{typeCode}</Badge>
            <span className="text-xs text-muted-foreground">{typeLabel}</span>
          </div>
          <p className="whitespace-pre-wrap break-words text-sm leading-6">{label}</p>
          {description ? (
            <p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">
              {description}
            </p>
          ) : null}
          {children.length > 0 ? (
            <div className="mt-3 grid gap-2 border-t pt-3">
              <Children children={children} depth={depth} />
            </div>
          ) : null}
        </article>
      );

    case "IMAGE":
      return (
        <figure className="min-w-0 overflow-hidden rounded-lg border bg-muted">
          <div className="relative grid aspect-[4/3] place-items-center overflow-hidden bg-muted">
            {imageUrl ? (
              <img
                className="size-full object-contain"
                src={imageUrl}
                alt={label === "Image" ? "" : label}
                loading="lazy"
                referrerPolicy="no-referrer"
              />
            ) : (
              <div
                className="grid place-items-center gap-2 text-muted-foreground"
                aria-hidden="true"
              >
                <ImageIcon className="size-7" />
                <span className="text-xs">No preview</span>
              </div>
            )}
          </div>
          <figcaption className="flex items-start justify-between gap-3 border-t bg-card p-3">
            <span className="min-w-0 break-words text-sm">{label}</span>
            <Badge variant="outline">{typeCode}</Badge>
          </figcaption>
        </figure>
      );

    case "FILE": {
      const fileName = getFileName(node);
      const fileSize = getFileSize(node);
      return (
        <article className="min-w-0 rounded-lg border bg-card p-3">
          <div className="flex items-start gap-3">
            <div className="grid size-9 shrink-0 place-items-center rounded-md bg-muted">
              <FileText className="size-4 text-muted-foreground" />
            </div>
            <div className="min-w-0 flex-1">
              {linkUrl ? (
                <a
                  className="block truncate rounded text-sm font-medium text-primary underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  href={linkUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  title={fileName}
                >
                  {fileName}
                </a>
              ) : (
                <p className="truncate text-sm font-medium" title={fileName}>
                  {fileName}
                </p>
              )}
              {fileSize ? (
                <p className="mt-1 font-mono text-xs text-muted-foreground">{fileSize}</p>
              ) : null}
            </div>
            <Badge variant="outline">{typeCode}</Badge>
          </div>
        </article>
      );
    }

    case "LINK": {
      const linkHost = linkUrl ? new URL(linkUrl).hostname : undefined;
      return (
        <article className="min-w-0 rounded-lg border bg-card p-3">
          <div className="mb-2 flex items-center justify-between gap-2">
            <Badge variant="outline">{typeCode}</Badge>
            {linkHost ? (
              <span className="max-w-44 truncate font-mono text-xs text-muted-foreground">
                {linkHost}
              </span>
            ) : null}
          </div>
          {linkUrl ? (
            <a
              className="inline-flex rounded text-sm font-medium text-primary underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              href={linkUrl}
              target="_blank"
              rel="noopener noreferrer"
            >
              {label}
              <ExternalLink className="ml-1 size-3.5" aria-hidden="true" />
            </a>
          ) : (
            <p className="text-sm font-medium">{label}</p>
          )}
          {description ? (
            <p className="mt-2 text-xs leading-5 text-muted-foreground">{description}</p>
          ) : null}
        </article>
      );
    }

    case "TASK_LIST":
      return (
        <section className="min-w-0 rounded-lg border bg-card p-3">
          <header className="mb-2 flex items-center justify-between gap-3">
            <Heading depth={depth} className="text-sm font-semibold">
              {label}
            </Heading>
            <Badge variant="outline">{typeCode}</Badge>
          </header>
          {children.length > 0 ? (
            <div className="grid gap-1">
              <Children children={children} depth={depth} />
            </div>
          ) : (
            <p className="py-2 text-xs text-muted-foreground">No tasks</p>
          )}
        </section>
      );

    case "TASK": {
      const completed = isTaskComplete(node);
      const dueDate = getTaskDueDate(node);
      return (
        <div className="flex min-w-0 items-start gap-2 rounded px-1.5 py-2">
          <input
            className="mt-0.5 size-4 shrink-0 accent-primary"
            type="checkbox"
            checked={completed}
            disabled
            aria-label={completed ? `已完成：${label}` : `未完成：${label}`}
          />
          <span
            className={
              completed
                ? "min-w-0 break-words text-sm leading-5 text-muted-foreground line-through"
                : "min-w-0 break-words text-sm leading-5"
            }
          >
            {label}
          </span>
          {dueDate ? (
            <time
              className="ml-auto shrink-0 font-mono text-[0.6875rem] text-muted-foreground"
              dateTime={dueDate}
              title={dueDate}
            >
              {formatCompactDate(dueDate)}
            </time>
          ) : null}
        </div>
      );
    }

    case "TABLE": {
      const rows = getTableRows(node);
      return (
        <section className="min-w-0 overflow-hidden rounded-lg border bg-card">
          <header className="flex items-center justify-between gap-3 border-b p-3">
            <Heading depth={depth} className="text-sm font-semibold">
              {label}
            </Heading>
            <Badge variant="outline">{typeCode}</Badge>
          </header>
          {rows.length > 0 ? (
            <div className="overflow-x-auto" tabIndex={0}>
              <table className="w-full border-collapse text-left text-xs">
                <tbody>
                  {rows.map((row, rowIndex) => (
                    <tr key={`${node.id}-row-${rowIndex}`}>
                      {row.map((cell, cellIndex) => (
                        <td
                          key={`${node.id}-cell-${rowIndex}-${cellIndex}`}
                          className="min-w-28 border-r border-b px-3 py-2 align-top last:border-r-0"
                        >
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : children.length > 0 ? (
            <div className="grid gap-2 p-3">
              <Children children={children} depth={depth} />
            </div>
          ) : (
            <p className="p-3 text-xs text-muted-foreground">Empty table</p>
          )}
        </section>
      );
    }

    case "COMMENT_THREAD": {
      const comments = getComments(node);
      return (
        <aside className="min-w-0 rounded-lg border-l-2 border-primary bg-muted p-3">
          <header className="mb-2 flex items-center justify-between gap-3">
            <Heading
              depth={depth}
              className="text-xs font-semibold tracking-wide text-muted-foreground uppercase"
            >
              {label}
            </Heading>
            <span className="font-mono text-xs text-muted-foreground">{comments.length}</span>
          </header>
          {comments.length > 0 ? (
            <ol className="grid list-none gap-2">
              {comments.map((comment) => (
                <li key={comment.id} className="rounded-md border bg-card p-2.5">
                  {comment.author || comment.createdAt ? (
                    <div className="mb-1.5 flex flex-wrap items-center justify-between gap-2 text-[0.6875rem] text-muted-foreground">
                      {comment.author ? (
                        <span className="font-medium">{comment.author}</span>
                      ) : null}
                      {comment.createdAt ? (
                        <time
                          className="font-mono"
                          dateTime={comment.createdAt}
                          title={comment.createdAt}
                        >
                          {formatCompactDate(comment.createdAt)}
                        </time>
                      ) : null}
                    </div>
                  ) : null}
                  <p className="whitespace-pre-wrap break-words text-xs leading-5">
                    {comment.text}
                  </p>
                </li>
              ))}
            </ol>
          ) : (
            <p className="text-xs text-muted-foreground">No comments</p>
          )}
          {children.length > 0 ? (
            <div className="mt-2 grid gap-2 border-t pt-2">
              <Children children={children} depth={depth} />
            </div>
          ) : null}
        </aside>
      );
    }

    case "SKELETON":
      return (
        <div className="min-w-0 rounded-lg border border-dashed bg-muted px-3 py-4 text-center">
          <Badge variant="outline">{typeCode}</Badge>
          <p className="mt-2 text-xs text-muted-foreground">
            This item was not returned by the source.
          </p>
        </div>
      );

    case "UNKNOWN": {
      const unknownKind = getUnknownKind(node);
      return (
        <article className="min-w-0 rounded-lg border border-dashed bg-card p-3">
          <div className="flex items-center justify-between gap-2">
            <Badge variant="outline">{typeCode}</Badge>
            {unknownKind ? (
              <span className="max-w-40 truncate font-mono text-xs text-muted-foreground">
                {unknownKind}
              </span>
            ) : null}
          </div>
          <p className="mt-3 break-words text-sm">{label}</p>
          <code className="mt-2 block max-w-full truncate font-mono text-[0.6875rem] text-muted-foreground">
            {node.id}
          </code>
          {children.length > 0 ? (
            <div className="mt-3 grid gap-2 border-t pt-3">
              <Children children={children} depth={depth} />
            </div>
          ) : null}
        </article>
      );
    }

    default:
      return assertNever(node);
  }
}

function assertNever(value: never): never {
  throw new Error(`Unsupported normalized node: ${String(value)}`);
}

// apps/playground/src/components/board/BoardElement.vue
<script setup lang="ts">
import type { MilanoteNode } from "@milanote-api/parser";
import { computed } from "vue";

import {
  formatCompactDate,
  getComments,
  getFileName,
  getFileSize,
  getImageUrl,
  getLinkUrl,
  getNodeChildren,
  getNodeDescription,
  getNodeLabel,
  getNodeTypeCode,
  getNodeTypeLabel,
  getTableRows,
  getTaskDueDate,
  getUnknownKind,
  isTaskComplete,
} from "../../utils/boardModel.ts";

const props = withDefaults(
  defineProps<{
    depth?: number;
    node: MilanoteNode;
  }>(),
  { depth: 0 },
);

const children = computed(() => getNodeChildren(props.node));
const label = computed(() => getNodeLabel(props.node));
const description = computed(() => getNodeDescription(props.node));
const typeCode = computed(() => getNodeTypeCode(props.node.type));
const typeLabel = computed(() => getNodeTypeLabel(props.node.type));
const imageUrl = computed(() => getImageUrl(props.node));
const imageAlt = computed(() => (label.value === "Image" ? "" : label.value));
const linkUrl = computed(() => getLinkUrl(props.node));
const linkHost = computed(() => {
  if (!linkUrl.value) {
    return undefined;
  }

  return new URL(linkUrl.value).hostname;
});
const fileName = computed(() => getFileName(props.node));
const fileSize = computed(() => getFileSize(props.node));
const taskComplete = computed(() => isTaskComplete(props.node));
const taskDueDate = computed(() => getTaskDueDate(props.node));
const tableRows = computed(() => getTableRows(props.node));
const comments = computed(() => getComments(props.node));
const unknownKind = computed(() => getUnknownKind(props.node));
const headingLevel = computed(() => Math.min(props.depth + 2, 6));
</script>

<template>
  <section v-if="node.type === 'COLUMN'" class="surface-panel min-w-0 p-3">
    <header class="mb-3 flex items-start justify-between gap-3 border-b border-base pb-3">
      <div class="min-w-0">
        <span class="type-badge">{{ typeCode }}</span>
        <div class="mt-2 break-words text-sm font-750" role="heading" :aria-level="headingLevel">
          {{ label }}
        </div>
      </div>
      <span class="technical-value shrink-0 text-xs color-soft">
        {{ children.length }}
      </span>
    </header>

    <div v-if="children.length > 0" class="grid gap-2.5">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
    <p v-else class="m-0 py-5 text-center text-xs color-soft">Empty column</p>
  </section>

  <section v-else-if="node.type === 'BOARD'" class="surface-panel min-w-0 p-3">
    <header class="mb-3 flex items-center justify-between gap-3">
      <div
        class="min-w-0 truncate text-sm font-750"
        role="heading"
        :aria-level="headingLevel"
        :title="label"
      >
        {{ label }}
      </div>
      <span class="type-badge">{{ typeCode }}</span>
    </header>
    <div class="grid gap-2.5">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
  </section>

  <article
    v-else-if="node.type === 'CARD'"
    class="min-w-0 rounded-md border border-base bg-[var(--c-accent-soft)]/35 p-3"
  >
    <div class="mb-2 flex items-center justify-between gap-2">
      <span class="type-badge">{{ typeCode }}</span>
      <span class="text-xs color-soft">{{ typeLabel }}</span>
    </div>
    <p class="m-0 whitespace-pre-wrap break-words text-sm leading-6">{{ label }}</p>
    <p v-if="description" class="mb-0 mt-2 whitespace-pre-wrap text-xs leading-5 color-soft">
      {{ description }}
    </p>
    <div v-if="children.length > 0" class="mt-3 grid gap-2 border-t border-base pt-3">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
  </article>

  <figure
    v-else-if="node.type === 'IMAGE'"
    class="m-0 min-w-0 overflow-hidden rounded-md border border-base bg-secondary"
  >
    <div class="relative aspect-[4/3] grid place-items-center overflow-hidden bg-secondary">
      <img
        v-if="imageUrl"
        class="h-full w-full object-contain"
        :src="imageUrl"
        :alt="imageAlt"
        loading="lazy"
        referrerpolicy="no-referrer"
      />
      <div v-else class="grid place-items-center gap-2 color-soft" aria-hidden="true">
        <span class="technical-value text-2xl">IMG</span>
        <span class="text-xs">No preview</span>
      </div>
    </div>
    <figcaption class="flex items-start justify-between gap-3 border-t border-base bg-elevated p-3">
      <span class="min-w-0 break-words text-sm">{{ label }}</span>
      <span class="type-badge shrink-0">{{ typeCode }}</span>
    </figcaption>
  </figure>

  <article
    v-else-if="node.type === 'FILE'"
    class="min-w-0 rounded-md border border-base bg-elevated p-3"
  >
    <div class="flex items-start gap-3">
      <span class="type-badge shrink-0">{{ typeCode }}</span>
      <div class="min-w-0 flex-1">
        <a
          v-if="linkUrl"
          class="focus-ring block truncate rounded text-sm font-650 color-active underline-offset-3 hover:underline"
          :href="linkUrl"
          target="_blank"
          rel="noopener noreferrer"
          :title="fileName"
        >
          {{ fileName }}
        </a>
        <p v-else class="m-0 truncate text-sm font-650" :title="fileName">
          {{ fileName }}
        </p>
        <p v-if="fileSize" class="technical-value mb-0 mt-1 text-xs color-soft">
          {{ fileSize }}
        </p>
      </div>
    </div>
  </article>

  <article
    v-else-if="node.type === 'LINK'"
    class="min-w-0 rounded-md border border-base bg-elevated p-3"
  >
    <div class="mb-2 flex items-center justify-between gap-2">
      <span class="type-badge">{{ typeCode }}</span>
      <span
        v-if="linkHost"
        class="technical-value max-w-44 truncate text-xs color-soft"
        :title="linkHost"
      >
        {{ linkHost }}
      </span>
    </div>
    <a
      v-if="linkUrl"
      class="focus-ring block rounded text-sm font-650 color-active underline-offset-3 hover:underline"
      :href="linkUrl"
      target="_blank"
      rel="noopener noreferrer"
    >
      {{ label }}
      <span aria-hidden="true"> ↗</span>
    </a>
    <p v-else class="m-0 text-sm font-650">{{ label }}</p>
    <p v-if="description" class="mb-0 mt-2 text-xs leading-5 color-soft">
      {{ description }}
    </p>
  </article>

  <section
    v-else-if="node.type === 'TASK_LIST'"
    class="min-w-0 rounded-md border border-base bg-elevated p-3"
  >
    <header class="mb-2 flex items-center justify-between gap-3">
      <div class="text-sm font-700" role="heading" :aria-level="headingLevel">
        {{ label }}
      </div>
      <span class="type-badge">{{ typeCode }}</span>
    </header>
    <div v-if="children.length > 0" class="grid gap-1">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
    <p v-else class="m-0 py-2 text-xs color-soft">No tasks</p>
  </section>

  <div v-else-if="node.type === 'TASK'" class="flex min-w-0 items-start gap-2 rounded px-1.5 py-2">
    <input
      class="mt-0.5 h-4 w-4 shrink-0 accent-[var(--c-accent)]"
      type="checkbox"
      :checked="taskComplete"
      disabled
      :aria-label="taskComplete ? `已完成：${label}` : `未完成：${label}`"
    />
    <span
      class="min-w-0 break-words text-sm leading-5"
      :class="taskComplete ? 'line-through color-soft' : 'color-base'"
    >
      {{ label }}
    </span>
    <time
      v-if="taskDueDate"
      class="technical-value ml-auto shrink-0 text-[0.6875rem] color-soft"
      :datetime="taskDueDate"
      :title="taskDueDate"
    >
      {{ formatCompactDate(taskDueDate) }}
    </time>
  </div>

  <section
    v-else-if="node.type === 'TABLE'"
    class="min-w-0 overflow-hidden rounded-md border border-base bg-elevated"
  >
    <header class="flex items-center justify-between gap-3 border-b border-base p-3">
      <div class="text-sm font-700" role="heading" :aria-level="headingLevel">
        {{ label }}
      </div>
      <span class="type-badge">{{ typeCode }}</span>
    </header>
    <div v-if="tableRows.length > 0" class="overflow-x-auto" tabindex="0">
      <table class="w-full border-collapse text-left text-xs">
        <tbody>
          <tr v-for="(row, rowIndex) in tableRows" :key="rowIndex">
            <td
              v-for="(cell, cellIndex) in row"
              :key="cellIndex"
              class="min-w-28 border-b border-r border-base px-3 py-2 align-top last:border-r-0"
            >
              {{ cell }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div v-else-if="children.length > 0" class="grid gap-2 p-3">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
    <p v-else class="m-0 p-3 text-xs color-soft">Empty table</p>
  </section>

  <aside
    v-else-if="node.type === 'COMMENT_THREAD'"
    class="min-w-0 rounded-md border-l-2 border-[var(--c-accent)] bg-secondary p-3"
  >
    <header class="mb-2 flex items-center justify-between gap-3">
      <div
        class="text-xs font-700 uppercase tracking-wide color-soft"
        role="heading"
        :aria-level="headingLevel"
      >
        {{ label }}
      </div>
      <span class="technical-value text-xs color-soft">{{ comments.length }}</span>
    </header>
    <ol v-if="comments.length > 0" class="m-0 grid list-none gap-2 p-0">
      <li
        v-for="comment in comments"
        :key="comment.id"
        class="rounded border border-base bg-elevated p-2.5"
      >
        <div
          v-if="comment.author || comment.createdAt"
          class="mb-1.5 flex flex-wrap items-center justify-between gap-2 text-[0.6875rem] color-soft"
        >
          <span v-if="comment.author" class="font-650">{{ comment.author }}</span>
          <time
            v-if="comment.createdAt"
            class="technical-value"
            :datetime="comment.createdAt"
            :title="comment.createdAt"
          >
            {{ formatCompactDate(comment.createdAt) }}
          </time>
        </div>
        <p class="m-0 whitespace-pre-wrap break-words text-xs leading-5">
          {{ comment.text }}
        </p>
      </li>
    </ol>
    <p v-else class="m-0 text-xs color-soft">No comments</p>
    <div v-if="children.length > 0" class="mt-2 grid gap-2 border-t border-base pt-2">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
  </aside>

  <div
    v-else-if="node.type === 'SKELETON'"
    class="min-w-0 rounded-md border border-dashed border-base bg-secondary px-3 py-4 text-center"
  >
    <span class="type-badge">{{ typeCode }}</span>
    <p class="mb-0 mt-2 text-xs color-soft">This item was not returned by the source.</p>
  </div>

  <article v-else class="min-w-0 rounded-md border border-dashed border-base bg-elevated p-3">
    <div class="flex items-center justify-between gap-2">
      <span class="type-badge">{{ typeCode }}</span>
      <span
        v-if="unknownKind"
        class="technical-value max-w-40 truncate text-xs color-soft"
        :title="unknownKind"
      >
        {{ unknownKind }}
      </span>
    </div>
    <p class="mb-0 mt-3 break-words text-sm">{{ label }}</p>
    <code
      class="technical-value mt-2 block max-w-full truncate text-[0.6875rem] color-soft"
      :title="node.id"
    >
      {{ node.id }}
    </code>
    <div v-if="children.length > 0" class="mt-3 grid gap-2 border-t border-base pt-3">
      <BoardElement v-for="child in children" :key="child.id" :node="child" :depth="depth + 1" />
    </div>
  </article>
</template>
